CREATE TABLE stg.listings
(
    stg_listing_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    batch_id INT NOT NULL REFERENCES stg.batch(batch_id),
    property_id TEXT, 
    status TEXT, 
    style TEXT, 
    full_street_line TEXT, 
    street TEXT, 
    unit TEXT, 
    city TEXT, 
    state TEXT, 
    zip_code TEXT, 
    beds TEXT, 
    full_baths TEXT, 
    half_baths TEXT, 
    sqft TEXT, 
    year_built TEXT, 
    days_on_mls TEXT, 
    list_price TEXT, 
    list_date TEXT, 
    pending_date TEXT, 
    sold_price TEXT, 
    last_sold_date TEXT, 
    last_sold_price TEXT, 
    last_status_change_date TEXT, 
    last_update_date TEXT, 
    new_construction TEXT, 
    lot_sqft TEXT, 
    price_per_sqft TEXT, 
    latitude TEXT, 
    longitude TEXT, 
    county TEXT, 
    stories TEXT, 
    hoa_fee TEXT, 
    parking_garage TEXT
)